// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeminjamanRuanganBackend.Data;

#nullable disable

namespace _2026_PeminjamanRuangan_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210134608_SeedPeminjaman")]
    partial class SeedPeminjaman
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeminjamanRuanganBackend.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ruangan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalKembali")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TanggalPinjam")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Peminjamans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NamaPeminjam = "Safa",
                            Ruangan = "Lab A",
                            Status = "Diterima",
                            TanggalKembali = new DateTime(2026, 2, 11, 20, 46, 7, 671, DateTimeKind.Local).AddTicks(3462),
                            TanggalPinjam = new DateTime(2026, 2, 10, 20, 46, 7, 670, DateTimeKind.Local).AddTicks(1775)
                        },
                        new
                        {
                            Id = 2,
                            NamaPeminjam = "Budi",
                            Ruangan = "Lab B",
                            Status = "Ditolak",
                            TanggalKembali = new DateTime(2026, 2, 12, 20, 46, 7, 671, DateTimeKind.Local).AddTicks(4319),
                            TanggalPinjam = new DateTime(2026, 2, 10, 20, 46, 7, 671, DateTimeKind.Local).AddTicks(4317)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
